# docker-compose.yml
version: '3'

services:
  serving:
#    volumes:
#      - ./vol1:/vol1
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
#      args:
#        ARG: --env COMET_API_KEY=$COMET_API_KEY
    image: ift6758/serving
    ports:
      - 8080:8080
    environment:
      - COMET_API_KEY=$COMET_API_KEY
###### Uncomment below when you're ready to add the final notebook container to your docker compose
  jupyter:
#    volumes:
#      - ./vol1:/vol1
    build:
      context: ./
      dockerfile: ./Dockerfile.jupyter
##      args:
##        ARG: <ARG>
    image: ift6758/jupyter
    ports:
      - 8081:8081
#    environment:
#      - OTHER_DOCKER_ENV_VAR = ${OTHER_LOCAL_ENV_VAR}
      

     
